apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
  labels:
    app: payment-service-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30001
  selector:
    app: payment-service